export const CRITERIA_NAMES = [
    "COMMUNICATION SKILLS",
    "LEADERSHIP SKILLS",
    "PLANNING/DECISION MAKING",
    "WORK-ORIENTED/DEDICATION & COMMITMENT",
    "QUALITY OF WORK",
    "CREATIVE, SIMPLE & EFFICIENT",
    "PERSONAL CONDUCT/BEHAVIOR",
    "SERVICE-ORIENTED/WORK ATTITUDE",
    "MORAL VALUES",
    "TEAMWORK",
    "MANNER & APPEARANCE"
];

export const APPLICANTS_PER_PAGE = 10;
export const ADMIN_SUBMISSIONS_CHUNK_SIZE = 20;
export const ADMIN_APPLICANTS_CHUNK_SIZE = 20;
export const ADMIN_ACCOUNTS_CHUNK_SIZE = 20;
export const ADMIN_MODAL_CHUNK_SIZE = 10;

export const MAX_POINTS = [3, 2, 2, 1, 1, 1, 3, 2, 2, 2, 1];
