export const domElements = {
    views: {
        login: document.getElementById('login-view'),
        employee: document.getElementById('employee-view'),
        admin: document.getElementById('admin-view'),
        settings: document.getElementById('settings-view')
    },
    auth: {
        loginForm: document.getElementById('login-form'),
        loginUsername: document.getElementById('login-username'),
        loginPassword: document.getElementById('login-password')
    },
    employee: {
        welcome: document.getElementById('employee-welcome'),
        settingsBtn: document.getElementById('employee-settings'),
        logoutBtn: document.getElementById('employee-logout'),
        form: document.getElementById('rating-form'),
        preSubmitBtn: document.getElementById('pre-submit-btn'),
        liveTotal: document.getElementById('live-total'),
        numberInputs: null, // will be dynamic
        raterName: document.getElementById('form-rater-name'),
        raterRole: document.querySelector('.rater-role'),
        dynamicTable: document.getElementById('dynamic-rating-table'),
        prevPageBtn: document.getElementById('prev-page-btn'),
        nextPageBtn: document.getElementById('next-page-btn'),
        pageIndicator: document.getElementById('page-indicator'),
        clearAllBtn: document.getElementById('clear-all-ratings-btn'),
        passwordWarning: document.getElementById('password-warning')
    },
    admin: {
        el: document.getElementById('admin-view'),
        welcome: document.getElementById('admin-welcome'),
        logoutBtn: document.getElementById('admin-logout'),
        tbody: document.getElementById('admin-submissions-content'),
        divisionTabsNav: document.getElementById('division-tabs-nav'),
        deleteAllSubmissionsBtn: document.getElementById('delete-all-submissions-btn'),
        emptyState: document.getElementById('no-ratings-msg'),
        settingsBtn: document.getElementById('admin-settings'),
        exportBtn: document.getElementById('export-excel-btn'),
        historyBtn: document.getElementById('history-btn'),
        historyTab: document.getElementById('admin-tab-history'),
        backToSubmissionsFromHistory: document.getElementById('back-to-submissions-from-history'),
        historyTbody: document.getElementById('history-tbody'),
        restoreAllBtn: document.getElementById('restore-all-btn'),
        deleteAllHistoryBtn: document.getElementById('delete-all-history-btn'),
        noHistoryMsg: document.getElementById('no-history-msg'),
        applicantHistoryBtn: document.getElementById('applicant-history-btn'),
        applicantHistoryModal: document.getElementById('applicant-history-modal'),
        applicantHistoryClose: document.querySelector('#applicant-history-modal .close-modal'),
        applicantHistoryTbody: document.getElementById('applicant-history-tbody'),
        applicantHistoryContainer: document.getElementById('applicant-history-container'),
        restoreAllApplicantsBtn: document.getElementById('restore-all-applicants-btn'),
        deleteAllApplicantsHistoryBtn: document.getElementById('delete-all-applicants-history-btn'),
        noApplicantHistoryMsg: document.getElementById('no-applicant-history-msg'),
        applicantsTbody: document.getElementById('admin-applicants-tbody'),
        noApplicantsMsg: document.getElementById('no-applicants-msg'),
        openAddApplicantBtn: document.getElementById('open-add-applicant-btn'),
        deleteAllApplicantsBtn: document.getElementById('delete-all-applicants-btn'),
        addApplicantModal: document.getElementById('add-applicant-modal'),
        addApplicantForm: document.getElementById('add-applicant-form'),
        newApplicantName: document.getElementById('new-applicant-name'),
        newApplicantPosition: document.getElementById('new-applicant-position'),
        newApplicantDivision: document.getElementById('new-applicant-division'),
        newApplicantBatch: document.getElementById('new-applicant-batch'),
        openAddBatchBtn: document.getElementById('open-add-batch-btn'),
        addBatchModal: document.getElementById('add-batch-modal'),
        addBatchForm: document.getElementById('add-batch-form'),
        addBatchClose: document.querySelector('#add-batch-modal .close-modal'),
        newBatchName: document.getElementById('new-batch-name'),
        batchesFolderView: document.getElementById('batches-folder-view'),
        batchContentsView: document.getElementById('batch-contents-view'),
        batchesGrid: document.getElementById('batches-grid'),
        backToBatchesBtn: document.getElementById('back-to-batches-btn'),
        batchNameHeading: document.getElementById('batch-name-heading'),
        batchApplicantCount: document.getElementById('batch-applicant-count'),
        newCredentialInput: document.getElementById('new-credential-input'),
        addCredentialBtn: document.getElementById('add-credential-btn'),
        credentialsList: document.getElementById('credentials-list'),
        addApplicantClose: document.querySelector('#add-applicant-modal .close-modal'),
        accountsTbody: document.getElementById('admin-accounts-tbody'),
        accountsDivisionTabsNav: document.getElementById('accounts-division-tabs-nav'),
        noAccountsMsg: document.getElementById('no-accounts-msg'),
        exportAllBtn: document.getElementById('export-all-btn'),
        openAddAccountBtn: document.getElementById('open-add-account-btn'),
        addAccountModal: document.getElementById('add-account-modal'),
        addAccountForm: document.getElementById('add-account-form'),
        newAccountFullname: document.getElementById('new-account-fullname'),
        newAccountPosition: document.getElementById('new-account-position'),
        newAccountDivision: document.getElementById('new-account-division'),
        newAccountUsername: document.getElementById('new-account-username'),
        newAccountPassword: document.getElementById('new-account-password'),
        addAccountClose: document.querySelector('#add-account-modal .close-modal'),
        viewPasswordModal: document.getElementById('view-password-modal'),
        viewPasswordClose: document.querySelector('#view-password-modal .close-modal'),
        viewedEmployeeFullname: document.getElementById('viewed-employee-fullname'),
        viewedEmployeeUsername: document.getElementById('viewed-employee-username'),
        viewedEmployeePassword: document.getElementById('viewed-employee-password'),
        editEmployeeInfoModal: document.getElementById('edit-employee-info-modal'),
        editEmployeeInfoClose: document.querySelector('#edit-employee-info-modal .close-modal'),
        editEmployeeInfoForm: document.getElementById('edit-employee-info-form'),
        editEmployeeInfoUsername: document.getElementById('edit-employee-info-username'),
        editEmployeeInfoFullname: document.getElementById('edit-employee-info-fullname'),
        editEmployeeInfoDivision: document.getElementById('edit-employee-info-division'),
        editEmployeeInfoPosition: document.getElementById('edit-employee-info-position'),
        toggleSelectApplicantsBtn: document.getElementById('toggle-select-applicants-btn'),
        deleteSelectedApplicantsBtn: document.getElementById('delete-selected-applicants-btn'),
        moveSelectedApplicantsBtn: document.getElementById('move-selected-applicants-btn'),
        selectAllApplicantsCheckbox: document.getElementById('select-all-applicants-checkbox'),
        moveApplicantsModal: document.getElementById('move-applicants-modal'),
        moveApplicantsForm: document.getElementById('move-applicants-form'),
        moveApplicantsBatch: document.getElementById('move-applicants-batch'),
        moveApplicantsClose: document.querySelector('#move-applicants-modal .close-modal')
    },
    detailsTab: {
        el: document.getElementById('admin-tab-details'),
        body: document.getElementById('admin-tab-details-body'),
        backBtn: document.getElementById('back-to-submissions-btn')
    },
    detailsModal: {
        el: document.getElementById('details-modal'),
        body: document.getElementById('modal-details-body'),
        closeBtn: document.getElementById('close-details-modal')
    },
    confirmModal: {
        el: document.getElementById('confirm-modal'),
        title: document.getElementById('confirm-title'),
        message: document.getElementById('confirm-message'),
        okBtn: document.getElementById('confirm-ok'),
        cancelBtn: document.getElementById('confirm-cancel'),
        extraBtn: document.getElementById('confirm-extra')
    },
    settings: {
        form: document.getElementById('settings-form'),
        fullname: document.getElementById('settings-fullname'),
        positionGroup: document.getElementById('settings-position-group'),
        position: document.getElementById('settings-position'),
        divisionGroup: document.getElementById('settings-division-group'),
        division: document.getElementById('settings-division'),
        password: document.getElementById('settings-password'),
        passwordLabel: document.getElementById('settings-password-label'),
        backBtn: document.getElementById('settings-back'),
        deleteBtn: document.getElementById('delete-account-btn')
    },
    toast: document.getElementById('toast')
};

export const appState = {
    currentUser: JSON.parse(localStorage.getItem('ratingSystem_currentUser')) || null,
    existingUsers: [],
    allRatings: [],
    allApplicants: [],
    allBatches: [],
    activeBatchId: null,
    deletedRatings: [],
    deletedApplicants: [],
    currentFormCredentials: [],
    currentEmployeePage: 0,
    currentPendingApplicants: [],
    currentAdminTab: 'overview',
    adminSubmissionsObserver: null,
    loadedAdminSubmissions: 0,
    currentAdminSortedGroups: [],
    adminRaterSearchQuery: "",
    adminApplicantsObserver: null,
    loadedAdminApplicants: 0,
    adminApplicantSearchQuery: "",
    currentAdminFilteredApplicants: [],
    adminAccountsObserver: null,
    loadedAdminAccounts: 0,
    adminAccountSearchQuery: "",
    activeAccountDivisionTab: 'LTID',
    currentAdminFilteredAccounts: [],
    adminModalObserver: null,
    loadedAdminModalApplicants: 0,
    currentAdminModalApplicants: [],
    currentAdminDetailsPage: 0,
    currentAdminRaterRatings: [],
    currentAdminModalRater: "",
    currentAdminApplicantMap: new Map(),
    detailsReturnTarget: 'submissions',
    applicantSelectMode: false,
    selectedApplicants: new Set()
};
